on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: oven-sh/setup-bun@v2

      # - name: Use Node.js 20.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20.17.0'

      - name: 🔨 Build Project
        run: |
          bun install
          bun run favicon
          bun run build

      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action
      #   with:
      #     server: ${{ secrets.FTP_HOST }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.ftp_password }}
      #     local-dir: ${{ secrets.FTP_PATH }}
      #     exclude: |
      #       **/.git*
      #       **/.git*/**
      #       **/node_modules/**
      #       **/.pnpm-store/**